export {
  default as htmUniqueItemsReducer,
  setSearchText,
  setExactName,
  setMaxReqLevel,
  toggleCategory,
  toggleGroup,
  selectAllCategories,
  deselectAllCategories,
  setSelectedCategories,
  setIncludeCouponItems,
  selectSearchText,
  selectExactName,
  selectMaxReqLevel,
  selectSelectedCategories,
  selectSelectedCategoriesRaw,
  selectIsAllCategoriesSelected,
  selectIncludeCouponItems,
} from './htmUniqueItemsSlice';
